#!/bin/sh

highlight_js_path="$1"

if [ -z "$highlight_js_path" ] ; then
  echo "usage: ./build-highlight.js <path-to-highlight.js>"
  exit
fi

node "$highlight_js_path/tools/build.js" -t browser \
    bash clojure coffeescript cmake cpp cs css d delphi diff erlang \
    fortran fsharp go haskell ini java javascript lisp lua objectivec \
    perl php python ruby rust sql scala smalltalk tex vala xml \
  && cp "$highlight_js_path/build/highlight.pack.js" \
        ./src/main/webapp/js/highlight.pack.js
