name: Integration Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: maven:3.8.6-eclipse-temurin-17
    services:
      postgres:
        image: postgres:16
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres

    steps:
      - uses: actions/checkout@v2
      - name: Initialize database	
        env:
          PGHOST: postgres
          PGUSER: postgres
          PGPASSWORD: postgres
        run: |
          apt-get update
          apt-get install --yes --no-install-recommends postgresql-client
          createuser -d -S -R maxcom
          createuser -D -S -R linuxweb
          createuser -D -S -R jamwiki
          psql -c "ALTER USER maxcom WITH PASSWORD 'maxcom'" -U postgres template1
          psql -c "ALTER USER linuxweb WITH PASSWORD 'linuxweb'" -U postgres template1
          PGPASSWORD=maxcom createdb -U maxcom lor
          psql -c 'create extension hstore;' -U postgres lor
          psql -c 'create extension fuzzystrmatch;' -U postgres lor
          PGPASSWORD=maxcom psql -f sql/demo.db -U maxcom lor
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Build 
        run: mvn --batch-mode -DskipTests=true -Dmaven.javadoc.skip=true package
      - name: Test
        run: mvn --batch-mode verify
